version: '3.9'
services:
  bitbucket:
    image: atlassian/bitbucket:latest
    ports:
      - '7990:7990'
      - '7999:7999'
    environment:
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
      - JDBC_URL=jdbc:postgresql://postgresql:5432/bitbucket
    volumes:
      - 'bitbucket_data:/var/atlassian/application-data/bitbucket'
    networks:
      - bridge_network
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
        reservations:
          cpus: 0.5
          memory: 256M
  postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bitbucket
      - POSTGRESQL_DATABASE=bitbucket
    networks:
      - bridge_network
volumes:
  bitbucket_data:
    driver: local
  postgresql_data:
    driver: local
networks:
  bridge_network:
    driver: bridge