version: '3.9'
services:
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus_data:/opt/bitnami/prometheus/data'
      - './prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml'
    networks:
      - prometheus_network
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - prometheus_network

volumes:
  prometheus_data:
    driver: local
networks:
  prometheus_network:
    driver: bridge
    