version: '3.9'

services:
  jenkins:
    image: docker.io/bitnami/jenkins:2
    healthcheck:
      test: ["CMD", "curl --fail http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local